googler-gazzzza/coding-challenge

- README.md
github를 이용한 알고리즘 스터디 process 정리 입니다!
> 프로젝트 README 정리

- 70_climbing_stairs/koronya.js
> solve 70. Climbing Stairs

- 31_next_permutation/kongddeok.hpp
> Create kongddeok.hpp on the 31. next permutation

- 70_climbing_stairs/yalla.java
> solve problem. leetcode 70.climbing stairs

- 179_largest_number/hsh2438.py
정렬에서 bubble sort를 썼는데, quick sort로 추후에 수정도 해보겠습니다!
> https://leetcode.com/problems/largest-number

- leetcode/46_permutations/hsh2438.py
https://leetcode.com/problems/permutations
> hsh2438 46

- leetcode/easy/771_jewels_and_stones/hsh2438.py
> https://leetcode.com/problems/jewels-and-stones/

- leetcode/medium/64_minimum_path_sum/hsh2438.py
> https://leetcode.com/problems/minimum-path-sum/

- leetcode/easy/268_missing_number/kdd.hpp
> Create kdd.hpp on the 268. missig number

- leetcode/hard/4_median_of_two_sorted_arrays/kdd.hpp
> Create kdd.hpp on the 4. median of two sorted arrays

- codewars/7kyu/alphabetical-addition/dduck_alphabetical-addition.js
- codewars/7kyu/alphabetical-addition/dduck_alphabetical-addition.py
https://www.codewars.com/kata/alphabetical-addition
> feat(codewars/7kyu): alphabetical-addition.[js, py]

- 176_second_highest_salary/dongho.sql
- 177._nth_highest_salary/dongho.sql
- 180_consecutive_numbers/dongho.sql
- 185._department_top_three_salaries/dongho.sql
- 197_rising_temperature/dongho.sql
Crete 185. Department Top Three Salaries
> 185. Department Top Three Salaries

- leetcode/easy/268_missing_number/dosun.py
- leetcode/easy/69_sqrt/dosun.py
> [easy] Solved 268. Missing Number

- leetcode/203_Remove_Linked_List_Elements/yalla.java
> [easy] Solved 203. Remove Linked List Elements

- leetcode/easy/13_roman_to_integer/dduck_roman-to-integer.js
- leetcode/easy/268_missing_number/dduck_missing-number.js
https://leetcode.com/problems/missing-number/
> feat(leetcode/top-interview-questions/easy): missing-number.js

- leetcode/easy/206_reverse_linked_list/hsh2438.py
- leetcode/easy/509_fibonacci_number/hsh2438.py
> Hsh2438 206

- leetcode/medium/238_product_of_array_except_self/hsh2438.py
나누기는 쓰면 안되고, output arrary를 제외하고는 constant space만 쓰라는 조건이 있어서 조금 까다로웠네요.
> https://leetcode.com/problems/product-of-array-except-self/

- codewars/8kyu/my-head-is-at-the-wrong-end/dduck_my-head-is-at-the-wrong-end.js
https://www.codewars.com/kata/my-head-is-at-the-wrong-end
> feat(codewars/8kyu): my-head-is-at-the-wrong-end.js

- leetcode/easy/206_reverse_linked_list/yalla.java
> [easy] solve 206. Reverse Linked List

- leetcode/medium/36_valid_sudoku/hsh2438.py
> https://leetcode.com/problems/valid-sudoku/

- codewars/8kyu/abbreviate-a-two-word-name/dduck_abbreviate-a-tow-word-name.js
- codewars/8kyu/abbreviate-a-two-word-name/dduck_abbreviate-a-tow-word-name.py
- codewars/8kyu/abbreviate-a-two-word-name/dduck_abbreviate-a-tow-word-name.rs
https://www.codewars.com/kata/abbreviate-a-two-word-name/
> feat(codewars/8kyu/abbreviate-a-tow-word-name.[js, py])

- codewars/8kyu/convert-a-string-to-an-array/dduck_convert-a-string-to-an-array.js
- codewars/8kyu/convert-a-string-to-an-array/dduck_convert-a-string-to-an-array.py
- codewars/8kyu/convert-a-string-to-an-array/dduck_convert-a-string-to-an-array.rs
https://www.codewars.com/kata/convert-a-string-to-an-array/
> feat(codewars/8kyu/convert-a-string-to-an-array.[js, py, rs]):

- leetcode/medium/200_number_of_islands/hsh2438.py
재귀를 싫어해서... 재귀를 안하고 하려니 어떻게 해야될지 생각이 잘 안나네요ㅠ
> https://leetcode.com/problems/number-of-islands/

- codewars/8kyu/make-upper-case/dduck_make-upper-case.js
https://www.codewars.com/kata/makeuppercase/
> feat(codewars/8kyu/make-upper-case.js):

- codewars/7kyu/shortest-word/dduck_shortest-word.js
- codewars/7kyu/shortest-word/dduck_shortest-word.py
- codewars/7kyu/shortest-word/dduck_shortest-word.rs
https://www.codewars.com/kata/shortest-word/
> feat(codewars/7kyu/shortest-word.js)

- leetcode/medium/230_kth_smallest_element_in_a_bst/hsh2438.py
> https://leetcode.com/problems/kth-smallest-element-in-a-bst/

- leetcode/easy/121_best_time_to_buy_and_sell_stock/dosun.py
- leetcode/easy/172_factorial_trailing_zeroes/dosun.py
- leetcode/easy/190_reverse_bits/dosun.py
- leetcode/easy/28_implement_strStr/dosun.py
- leetcode/easy/35_search_insert_position/dosun.py
> [easy] Solved 172. Factorial Trailing Zeroes

- leetcode/easy/104_maximum_depth_of_binary_tree/hsh2438.py
알고리즘을 풀다보니, 재귀를 싫어하지만 자꾸 재귀를 사용하게 되네요
> [Easy] 104. Maximum Depth of Binary Tree

- leetcode/medium/79_word_search/hsh2438.py
return을 1, 0으로 할 때는 시간 초과가 떴는데, True False를 반환하게 변경했는데 통과되네요
> [medium] 79. Word Search

- codewars/8kyu/calculate-bmi/dduck_calculate-bmi.js
https://www.codewars.com/kata/calculate-bmi/train/javascript
> feat(codewras/8kyu/calculate-bmi.js):

- codewars/6kyu/create-phone-number/create-phone-number.js
- codewars/6kyu/create-phone-number/dduck_create-phone-number.py
https://www.codewars.com/kata/create-phone-number/
> feat(codewars/6kyu/create-phone-number.js):·

- leetcode/easy/191_number_of_1_bits/dosun.py
> [easy] Solved 191. Number of 1 Bits

- codility/easy/1.cyclic_rotation/yalla.java
- codility/easy/1_odd_occurrences_in_array/yalla.java
Map으로 풀었다가 HashSet으로 바꿔서 풀어서 100% 맞췄어요
> Solved 1. odd_occurrences_in_array

- leetcode/easy/202_happy_number/dduck-happy-number.js
https://leetcode.com/problems/happy-number/
> feat(leetcode/top-interview-questions/easy/202_happy_number.js)

- leetcode/easy/181_employees_earning_more_than_their_managers/dongho.sql
- leetcode/easy/196_delete_duplicate_emails/dongho.sql
- leetcode/medium/178_rank_scores/dongho.sql
> [easy] solved 196_delete_duplicate_emails

- leetcode/easy/181_employees_earning_more_than_their_managers/dongho.sql
- leetcode/easy/183_customers_who_never_order/dongho183.sql
- leetcode/easy/196_delete_duplicate_emails/dongho.sql
> [easy] solved 181_employees_earning_more_than_their_managers

- leetcode/easy/181_employees_earning_more_than_their_managers/dongho.sql
- leetcode/easy/183_customers_who_never_order/dongho183.sql
- leetcode/easy/196_delete_duplicate_emails/dongho.sql
> [easy] solved 183_customers_who_never_order

- codewars/6kyu/tribonacci-sequence/dduck_tribonacci-sequence.js
https://www.codewars.com/kata/tribonacci-sequence/
> feat(codewars/6kyu/tribonacci-sequence.js)

- leetcode/easy/596_classes_more_than_5_students/dongho.sql
> [easy]  solved 596_classes_more_than_5_students

- codility/easy/1_FrogJmp/yalla.java
처음에 그냥 풀었더니 timeout나서 계산식으로 다시 풀었어요
> Solved 1. FrogJmp

- codewars/8kyu/sort-and-star/dduck_sort-and-star.js
https://www.codewars.com/kata/sort-and-star/
> feat(codewars/8kyu/sort-and-star/sort-and-star.js)

- codewars/8kyu/Easy SQL - Ordering/dongho.sql
- leetcode/easy/596_classes_more_than_5_students/dongho.sql
- leetcode/easy/620_not_boring_movies/dongho.sql
> [easy] solved 620_not_boring_movies

- codewars/8kyu/Easy SQL - Ordering/dongho.sql
- leetcode/easy/596_classes_more_than_5_students/dongho.sql
- leetcode/easy/620_not_boring_movies/dongho.sql
> Donghokim codewars 1 Easy SQL - Ordering

- leetcode/medium/73_set_matrix_zeroes/hsh2438.py
문제에서 in-place로 풀고, O(1)의 space만 추가로 사용해보라고 해서 그렇게 풀다보니 3중 포문까지 써야되네요...
> [Medium] 73. Set Matrix Zeroes

- leetcode/easy/13_roman_to_integer/runaway.js
leetcode 문제13 roman-to-integer 완료
> [easy] Solved 13. Roman to Integer

- codewars/8kyu/Easy SQL - Ordering/dongho.sql
- codewars/beta/Biggest in Each Column/dongho.sql
- leetcode/easy/596_classes_more_than_5_students/dongho.sql
- leetcode/easy/620_not_boring_movies/dongho.sql
> [beta] SQL Basics Biggest in Each Column  
